"""Initial migration

Revision ID: f70b39b0b724
Revises: 
Create Date: 2025-03-01 19:04:04.876615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70b39b0b724'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask_record',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hash', sa.Integer(), nullable=True),
        sa.Column('query_text', sa.Text(), nullable=False),
        sa.Column('response_text', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_ask_record_hash'), 'ask_record', ['hash'], unique=True)
    op.create_index(op.f('ix_ask_record_created_at'), 'ask_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_ask_record_updated_at'), 'ask_record', ['updated_at'], unique=False)

    op.create_table('chat_record',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('author', sa.Enum('USER', 'BOT', name='authorrole'), nullable=False),
        sa.Column('hash', sa.Integer(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_record_hash'), 'chat_record', ['hash'], unique=True)
    op.create_index(op.f('ix_chat_record_chat_id'), 'chat_record', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_record_created_at'), 'chat_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_record_updated_at'), 'chat_record', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_record_updated_at'), table_name='chat_record')
    op.drop_index(op.f('ix_chat_record_id'), table_name='chat_record')
    op.drop_index(op.f('ix_chat_record_hash'), table_name='chat_record')
    op.drop_index(op.f('ix_chat_record_created_at'), table_name='chat_record')
    op.drop_index(op.f('ix_chat_record_chat_id'), table_name='chat_record')
    op.drop_index(op.f('ix_chat_record_author'), table_name='chat_record')
    op.drop_table('chat_record')
    op.drop_index(op.f('ix_ask_record_updated_at'), table_name='ask_record')
    op.drop_index(op.f('ix_ask_record_id'), table_name='ask_record')
    op.drop_index(op.f('ix_ask_record_hash'), table_name='ask_record')
    op.drop_index(op.f('ix_ask_record_created_at'), table_name='ask_record')
    op.drop_table('ask_record')
    # ### end Alembic commands ###
